// <auto-generated />
namespace RGB.curso.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class atualizar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizar));
        
        string IMigrationMetadata.Id
        {
            get { return "201803271521027_atualizar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
